spring.application.name=neighborhood-watch-api

# Database Connection (Postgres)
spring.datasource.url=jdbc:postgresql://localhost:5432/neighborhood_watch
spring.datasource.username=radu
spring.datasource.password=4831

# Hibernate Configuration
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.security.enabled=false

spring.jackson.mapper.sort-properties-alphabetically=false
app.upload.dir=uploads

jwt.secret=f8e94d5e1f3c4a3b8bc8d7384c84c9e3e508a3f4a1b8d36e3c6c1f1f3e8d8fbc

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

